### ISSUE TITLE
Adding the lib to the PasteMyst README

### ISSUE THREAD

**Issue by CodeMyst** [dentolos19/PasteMystNet#2]
Hello, good job on making a C# wrapper for pastemyst! :D

Would if be ok if I added a link to this repo in the pastemyst's readme?

**Comment by dentolos19** [comment]
Yeah sure! I was about to ask the same but I was working on another project, it's nice to see that you did the first move!

**Comment by CodeMyst** [comment]
Awesome! Will add it then. 😄
