### ISSUE TITLE
update api to v2

### ISSUE THREAD

**Issue by CodeMyst** [dentolos19/PasteMystNet#4]
hey there. since pastemyst v2 just got release, you might want to update your lib to support the v2 api.

the api is backwards compatible so this lib shouldnt break, but v2 has many more features and a better api to go with it.

**Comment by dentolos19** [comment]
Alrighty then! I'll get started working on it.

**Comment by CodeMyst** [comment]
awesome! let me know if you need any help with it.

**Comment by dentolos19** [comment]
Alright, I've finished updating the library to support V2 API. If anything else, create another issue.
