### ISSUE TITLE
not possible to create a pasty with an empty title

### ISSUE THREAD

**Issue by CodeMyst** [dentolos19/PasteMystNet#5]
it should be possible to have a pasty with the title set to `""`, but that throws an exception.

**Comment by dentolos19** [comment]
Alright, I've fixed it with this [commit](https://github.com/dentolos19/PasteMystNet/commit/5c413d110a7d4e00854d1bd269fff69809b2af3c). I thought it was mandatory for the title to be filled. I will update the library until I get the paste editing functions working.

**Comment by CodeMyst** [comment]
the title field is mandatory in the request body, but it can be set to just `""` empty.
