### ISSUE TITLE
Error during serialization (android project)

### ISSUE THREAD

**Issue by TheDutchMagikarp** [dentolos19/PasteMystNet#6]
I'm using this package in Unity for a mobile (android) project. 
It works perfectly in the editor, but when I'm building to the target platform I get errors. After installing a newtonsoft.json version that should be fine with android (https://github.com/jilleJr/Newtonsoft.Json-for-Unity), I get the following exception on trying to create a paste:
`An error occurred during serialization: Unable to find a constructor to use for type PasteMystNet.PasteMystPaste. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'ownerId', line 1, position 11.`

Did I make a mistake somewhere and/or is this something I can fix on my end?

**Comment by TheDutchMagikarp** [comment]
The error I get with the nuget version of newtonsoft.json is this by the way, if it helps:
``An error occurred during serialization: Error getting value from '_tags' on 'PasteMystNet.PasteMystPasteForm'.``

**Comment by dentolos19** [comment]
Sorry for the late reply.

For now this is my solution, You should fork and add the project's source code into your Unity project (if you haven't already), and use the Unity version of `Newtonsoft.Json`. According to [this answer](https://stackoverflow.com/a/59815149/14035664), I think that what's happening is that the linker cannot see any use of your types constructor, so it removes it. To fix this, disable the bytecode stripping for that type using `link.xml` file.

```xml
<linker>
    <assembly fullname="PasteMystNet">

        <!-- disables stripping for the entire type -->
        <type fullname="PasteMystNet.PasteMystPaste" preserve="all"/>

    </assembly>
</linker>
```

Should there be any more problems, try to google it first. I hope this works out.

**Comment by TheDutchMagikarp** [comment]
Hi!
Thanks for your reply.
I've probably been googling with the wrong terms, because I hadn't found your linked answer.
It fixed the problem perfectly!
I also had to add the PasteMystPasty to the ``link.xml`` file.

The complete xml file that works is this:
```XML
<linker>
    <assembly fullname="PasteMystNet">

        <!-- disables stripping for the entire type -->
        <type fullname="PasteMystNet.PasteMystPaste" preserve="all"/>
        <type fullname="PasteMystNet.PasteMystPasty" preserve="all"/>

    </assembly>
</linker>
```

Thanks again for your help!
